name: Generate Podcast Feeds
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install Dependencies
        run:
          python3 - m pip install --upgrade pip
          python3 - m pip install PyYAML
          python3 -c 'import yaml'
      - name: Run Feed Generator
        run: python3 feed.py
      - name: Push Repo
        run:
          git config user.name learning-github-actions
          git config user.email learning-github-actions@github.com
          git add .
          git commit -m "Modified Feed"
          git push
