name: Generate Podcast Feeds = Previous
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install Dependencies
        run:
          python -m pip install --upgrade pip
          pip install pyyaml
      - name: Run Feed Generator
        run: python feed.py
      - name: Configure User Name
        run:
          git config user.name learning-github-actions
      - name: Configure User Email
        run:
          git config user.email learning-github-actions@github.com
      - name: Add changes
        run:
          git add .
      - name: Commit changes
        run:
          git commit -m "Modified Feed"
      - name: Push Repo
        run:
          git push
